# kubernetes/backstage.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: husky-example-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: husky-example-deploy
  template:
    metadata:
      labels:
        app: husky-example-deploy
    spec:
      containers:
        - name: backstage
          image: tiziano093/husky-example-commit
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: husky-example-deploy-service
spec:
  type: LoadBalancer
  selector:
    app: husky-example-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000